### ISSUE TITLE
raise Exception cause app crash

### ISSUE THREAD

**Issue by celikbas** [metebalci/pdftitle#36] opened 2023-08-28 06:13 UTC
is it possible to create an informative error message instead of application crash.

```
Traceback (most recent call last):
  File "/home/zk/.local/lib/python3.9/site-packages/pdftitle.py", line 701, in run
    title = get_title_from_file(args.pdf)
  File "/home/zk/.local/lib/python3.9/site-packages/pdftitle.py", line 581, in get_title_from_file
    return get_title_from_io(raw_file)
  File "/home/zk/.local/lib/python3.9/site-packages/pdftitle.py", line 476, in get_title_from_io
    dev.recover_last_paragraph()
  File "/home/zk/.local/lib/python3.9/site-packages/pdftitle.py", line 341, in recover_last_paragraph
    raise Exception("current block is None, this might be a bug. " +
Exception: current block is None, this might be a bug. please report it together with the pdf file
```

**Comment by metebalci** [comment] 2023-08-28 06:55
Can you share the pdf file causing this ?

**Comment by celikbas** [comment] 2023-08-28 07:47
Sorry, I couldn't anonymize the pdf. But can I ask you to provide an option to rise an error message instead of crash.

**Comment by metebalci** [comment] 2023-08-28 08:19
You can tell me the title etc. I might be able to find the pdf. The error indicates this is not supposed to happen, so I have to check why it happens first. The unexpected errors are reported like this for the moment.

**Comment by user202729** [comment] 2023-11-21 04:37
One possible PDF that causes this error is https://www.ams.org/about-us/6.14_LivingProof.pdf .

**Comment by metebalci** [comment] 2024-10-08 18:58
I do not know if it is the same problem the issue is created for but the problem with 6.14_LivingProof.pdf is it uses XForms/XObject. This problem is specifically mentioned in #39. I do not think I can fix this quick, but maybe I can improve the error handling and the message can say the document contains XForm so it is not supported yet. I created #41 to follow this up, so closing the issue now.

**Closed as completed by metebalci** 2024-10-08 18:58 UTC
