### ISSUE TITLE
Large text returned as title

### ISSUE THREAD

**Issue by impredicative** [metebalci/pdftitle#6] opened 2019-02-18 15:14 UTC
URL: http://www.pnas.org/content/pnas/suppl/2018/10/09/1809045115.DCSupplemental/pnas.1809045115.sapp.pdf

**The returned title is:**
1  SUPPORTIV E  INFORMATION   for Bruce N. Ames Perspective   SI - 1 - V itamin and Mineral D eficiencies   Numerous studies link  poor nutrition to a variety of diseases of aging , as shown in the following sampling of  recent references (1 - 12) .   SI - 2 - Triage T heory   Vitamin K  (phylloquinone) is necessary for the function of 16  enzymes .  A tri age rationing process is  support ed  by an analysis of the behavior of these enzymes under a mimic of vitamin K sho rtage (13) .  Recent  studies  provide additional support:  a  Mendelian Randomization (MR) epidemiology study showed that both all - cause and cardiovascular disease ( CVD )  mortality are caused by vitamin K1  inadeq uacy, and confirmed  that the low level of the inactive form of Mgp protein, which normally prevents arterial calcification, is diagnostic for vitamin K1 deficiency (14) .  I ncreased dietary intake of vitamin K1  and menaquinone (K2=MK2) and other derivatives (such  as MK7 in natto)  was associated wi th lower  all - cause cancer and CVD mortality (15) .  A study of 166 adolescents supports the CVD findings by showing that subclinical cardiac stru cture and function variables are most favorable at higher phylloquinone (vitamin K1) levels (16 ) .   Selenium  i s necessary for the function of  25 enzymes .  A  triage - related rationing was also shown to be operating in the case of selenium  (17) .  A  4 - year Randomized Clinical Trial (RCT)  (18)  of selenium supplemen tation (200  µ g/ d) +CoQ10 (2 00mg /d) significant ly reduced CVD mortality risk by more than 40 % ,  a nd a lso  significant ly  reduc ed  hypertension, IHD, impaired cardiac function, and diabetes in 443  elderly  people in rural Sweden  ( where  soil is low in selenium) du ring a follow - up time of 1 2 years ; i mprovement in CVD biomarkers, such as echocardiography and natriuretic peptide levels, was also observed.   SI - 3 - S urvival  V /M that are also L ongevity V /M   Vitamin D : A meta - analysis of vitamin D versus mortality in 5 Northern European countries (n=~29,000), using subjects of median age 62 years, showed that a blood level of 25(OH)D of less than 12 ng/ml was associated with maximum mortality, while levels between 30 to 40 ng/ml were as sociated with the lowest mortality (19) . Rodent eviden ce also showed that mutations in the vitamin D rec eptor in mice resulted in premature aging (20) .  A meta - analysis of 32 studies (n = ~500,000) on vitamin D and all - cause mortality showed th at t he mortality hazard ratio between subjects with the lowest quantile (<9 ng/ml) and those with  t he highest  (>50 ng/ml ) serum levels  of  25(OH)D  was 1.9 (p=0.001). Levels of 25(OH)D less than or equal to 30 ng/ml were associated with significantly higher (p <  .01 ) all - cause mortality than levels greater than 30 ng/ml (21) . A 12 - year German study of elderly individuals (n=9,579)  in a statistically simulated intervention with vitamin D  showed a large decrease in all - cause mortality and cancer (22) .   A 29 year - long study of 95,000 Danes showed that  a decreased plasma level of 25(OH)D  was associated with early mortality and an increased risk of ischemic heart disease and myocardial infarction (23) . An MR  analysis of this study  showed that a low 25(OH)D level was causally associated with all - cause mortality and cancer mortality

**Comment by metebalci** [comment] 2019-03-20 13:45
with v2.0 it does not return this, but it does not return title either. the problem is this document is very flat, I think all the text is written with a single font size.

**Comment by metebalci** [comment] 2019-03-29 14:42
Since I believe this issue cannot be solved at least with this project, I am closing this issue as wont-fix.

**Closed as completed by metebalci** 2019-03-29 14:42 UTC
